# Introduction

Now we have learned all the basic knowledge needed to utilize powerful Python packages for Data Science. We start with the NumPy (Numerical Python) package. Numpy is one of the core packages for numerical computing in Python.

Let's get started!

In [1]:
# Let's import the package

import numpy as np

# Basic Arrays

In [2]:
np.array([0, 1, 2, 3])

array([0, 1, 2, 3])

In [3]:
a = np.array([0, 1, 2, 3])
type(a)

numpy.ndarray

In [4]:
a.shape

(4,)

In [5]:
a[0]

0

In [8]:
a[3]

3

In [9]:
a[4]

IndexError: ignored

In [6]:
a[-1]

3

In [7]:
a[-4]

0

In [8]:
a[-5]

IndexError: index -5 is out of bounds for axis 0 with size 4

In [9]:
a[0:]

array([0, 1, 2, 3])

In [10]:
a[1:]

array([1, 2, 3])

In [11]:
a[:1]

array([0])

In [12]:
a[[-1]]

array([3])

In [13]:
a[:-1]

array([0, 1, 2])

In [19]:
a[::2]

array([0, 2])

In [14]:
a[1::2]

array([1, 3])

# Array Types

In [15]:
a = np.array([0, 1, 2, 3])
b = np.array([0.0, 0.1, 0.2, 0.3])

In [16]:
type(a)

numpy.ndarray

In [17]:
a.dtype

dtype('int32')

In [18]:
type(b)

numpy.ndarray

In [19]:
b.dtype

dtype('float64')

In [20]:
c = np.array([0, 1.1, 2, 3.8], dtype = float)
c

array([0. , 1.1, 2. , 3.8])

In [21]:
c.dtype

dtype('float64')

In [22]:
d = np.array([0, 1.1, 2, 3.8], dtype = int)
d

array([0, 1, 2, 3])

In [23]:
d.dtype

dtype('int32')

# Dimensions and Shapes

In [24]:
a = np.array([0, 1, 2, 3])

In [25]:
a.shape

(4,)

In [26]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7], 
    [8, 9, 10, 11]
])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
A.shape

(3, 4)

In [28]:
B = np.array([
    [
     [0, 1], 
     [2, 3],
     [4, 5]
    ],
    [
      
     [6, 7],
     [8, 9],
     [10, 11]
    ]
])
B

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [29]:
B.shape

(2, 3, 2)

In [30]:
B.ndim

3

In [37]:
B.size

12

# Indexing and Slicing of Matrices

In [31]:
A = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]     
])
A

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [32]:
A.shape

(2, 4)

In [33]:
A[0]

array([0, 1, 2, 3])

In [34]:
A[1]

array([4, 5, 6, 7])

In [35]:
A[:0]

array([], shape=(0, 4), dtype=int32)

In [36]:
A[:1]

array([[0, 1, 2, 3]])

In [37]:
A[:,0]

array([0, 4])

In [38]:
A[:,3]

array([3, 7])

In [39]:
A[0,0]

0

In [40]:
A[1, 3]

7

In [41]:
A[:,1:3]

array([[1, 2],
       [5, 6]])

In [42]:
A[0] = np.array([8, 9, 10, 11])
A

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7]])

In [43]:
A[1] = 98
A

array([[ 8,  9, 10, 11],
       [98, 98, 98, 98]])

# Statistics

In [44]:
a = np.array([0, 1, 2, 4])
a

array([0, 1, 2, 4])

In [45]:
a.sum()

7

In [46]:
a.mean()

1.75

In [47]:
a.std()

1.479019945774904

In [48]:
a.var()

2.1875

In [49]:
a.max()

4

In [50]:
a.min()

0

In [51]:
A = np.array([
     [0, 1, 2, 3],
     [4, 5, 6, 7],
     [8, 9, 10 , 11]
])
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
A.sum()

66

In [53]:
A.mean()

5.5

In [54]:
A.std()

3.452052529534663

In [55]:
A.var()

11.916666666666666

In [56]:
A.max()

11

In [57]:
A.min()

0

In [58]:
A.sum(axis=0)

array([12, 15, 18, 21])

In [59]:
A.sum(axis=1)

array([ 6, 22, 38])

In [60]:
A.mean(axis=0)

array([4., 5., 6., 7.])

In [61]:
A.max(axis = 1)

array([ 3,  7, 11])

# Linear Algebra

In [62]:
A = np.array([
    [0, 1, 2],
    [3, 4, 5]
])

B = np.array([
    [6, 7, 8],
    [9, 10, 11]
])

In [63]:
A

array([[0, 1, 2],
       [3, 4, 5]])

In [64]:
B

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [65]:
A + B

array([[ 6,  8, 10],
       [12, 14, 16]])

In [66]:
A - B

array([[-6, -6, -6],
       [-6, -6, -6]])

In [67]:
A * B

array([[ 0,  7, 16],
       [27, 40, 55]])

In [68]:
B.T

array([[ 6,  9],
       [ 7, 10],
       [ 8, 11]])

In [69]:
A @ (B.T)

array([[ 23,  32],
       [ 86, 122]])

In [70]:
A.T @ B

array([[27, 30, 33],
       [42, 47, 52],
       [57, 64, 71]])

# Useful functions

In [71]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [73]:
np.arange(5, 10, 2)

array([5, 7, 9])

In [74]:
np.arange(5, 10, 0.5)

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [75]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [76]:
np.arange(12).reshape(3, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [77]:
np.random.randint(0, 10, (10))

array([5, 4, 1, 9, 3, 4, 7, 5, 4, 0])

In [78]:
np.random.randint(0, 10, (5, 2))

array([[7, 5],
       [7, 6],
       [9, 9],
       [1, 8],
       [5, 0]])

In [79]:
np.random.rand(2, 4)

array([[0.02457845, 0.91794313, 0.72761682, 0.82596133],
       [0.35116726, 0.99634201, 0.88121915, 0.8148128 ]])

In [80]:
np.random.normal(0, 0.1, (10))

array([-0.15990281, -0.06683483, -0.07823551,  0.16104736,  0.06294051,
       -0.02201067,  0.13634397, -0.05680099,  0.11175325,  0.19477652])

In [81]:
np.random.normal(0, 0.1, (2, 5))

array([[-0.05394864, -0.10121218, -0.04506194, -0.06693263, -0.06075709],
       [ 0.04107558,  0.08867938,  0.05624264,  0.07166371, -0.20517376]])

In [82]:
np.random.uniform(0, 1, (3, 4))

array([[0.32925465, 0.33749335, 0.72038536, 0.68771036],
       [0.275732  , 0.0590511 , 0.70938263, 0.26922328],
       [0.68523784, 0.95729798, 0.83541974, 0.73621936]])

In [83]:
a = np.random.uniform(0, 1, (2, 5))
np.sort(a)

array([[0.24508975, 0.42651798, 0.79055066, 0.79790359, 0.85967151],
       [0.16514198, 0.28945723, 0.52826527, 0.64648956, 0.7082245 ]])

In [84]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [85]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.ones((2, 5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])